### ISSUE TITLE
Button does not show in Beatport

### ISSUE THREAD

**Issue by achmetinternet** [VxJasonxV/MusicBrainz-Track-Parsers#7]
Hi Jason,

not sure where to post the issue so here it is for you to see as well:

https://github.com/murdos/musicbrainz-userscripts/issues/24

Thanks for your help.

**Comment by VxJasonxV** [comment]
I'm subscribed to https://github.com/murdos/musicbrainz-userscripts, so I see issues and pull requests created there. This repository (my repository) is relevant to it's contents, e.g. all the Perl scripts. So we'll take care of it in murdos' repository.
